### PR TITLE
Removes liblognorm V1 rulebase support

### LINKED ISSUE #23: Liblognorm rulebase version 1 doesn't pass error information to java
**Description**
When using rulebase version 1 the normalization can fail without any error callbacks or return values that can be used to catch the C-library error as a java exception.

An example V1 rulebase:
`rule=regex:regex: %token:regex:abcd.fg%`
An example message to normalize using the rulebase:
`regex: 1234`
When the rulebase is used to normalize the message, the normalization method returns 0 noting that the normalization was a success but the normalized output is in fact in the error format. The liblognorm error callback does not receive any error logs either as the rulebase itself doesn't have any errors, the problem is in the normalization method that does not return an error code while still generating error information in the normalized output:
`{ "originalmsg": "regex: 1234", "unparsed-data": "1234" }`

A method to catch the error as an exception must be implemented.

### PR DESCRIPTION
**Pull request by Tiihott**
Includes:
- Removal of liblognorm V1 rulebase support from the project to fix issue #23 
- Tests for the changes.

In other words only V2 rulebase format is supported, usage of V1 rulebase will throw an exception.

### CODE REVIEW

File: src/main/java/com/teragrep/rsm_01/LognormFactory.java [hunk 1]
```diff
@@ -121,6 +125,27 @@ private void liblognormLoadSamples(Pointer ctx, String rulebase) {
             LOGGER.error("ln_loadSamples() returned error code <{}>", i);
             throw new IllegalArgumentException("ln_loadSamples() returned " + i + " instead of 0");
         }
+        // Check for version=2 line from rulebase.
+        checkRulebaseVersion(rulebase);
```
Comment (51-code) [inline src/main/java/com/teragrep/rsm_01/LognormFactory.java]: Could this function be called even before loading the samples, so the function would throw the exception immediately if version=2 is used?

File: src/main/java/com/teragrep/rsm_01/LognormFactory.java [hunk 2]
```diff
@@ -121,6 +125,27 @@ private void liblognormLoadSamples(Pointer ctx, String rulebase) {
...
+    }
+
+    private void checkRulebaseVersion(String rulebase) {
```
Comment (51-code) [inline src/main/java/com/teragrep/rsm_01/LognormFactory.java]: String rulebase is a bit ambiguous. Filename could be a better variable name. Or rulebaseFile.

**Review by 51-code — CHANGES_REQUESTED** [review]
Can `liblognormLoadSamplesFromString` also use the version=2, or is that just for the rulebase files?

**Comment by Tiihott** [comment]
> Can `liblognormLoadSamplesFromString` also use the version=2, or is that just for the rulebase files?

Liblognorm API has limited loading rulebase as a string to V2 only. So there is no need to add version=2 when string is used.

File: src/main/java/com/teragrep/rsm_01/LognormFactory.java (hunk 2 above)
Comment (Tiihott) [reply src/main/java/com/teragrep/rsm_01/LognormFactory.java]: Renamed to rulebaseFile in commit: 93298cc56c9b351b269d110b2b20e09748d65dc3

File: src/main/java/com/teragrep/rsm_01/LognormFactory.java (hunk 1 above)
Comment (Tiihott) [reply src/main/java/com/teragrep/rsm_01/LognormFactory.java]: Moved the method execution to happen before loading sample in commit: 93298cc56c9b351b269d110b2b20e09748d65dc3

**Review by 51-code — APPROVED** [review]
LGTM

**Review by kortemik — COMMENTED** [review]
there is no way to test loaded rulebase version before using it?

**Comment by Tiihott** [comment]
> there is no way to test loaded rulebase version before using it?

As far as I know there is no way to test the loaded rulebase version in Liblognorm other than checking the first line of the rulebase file. The Liblognorm API has very limited functionality on that regard, basically the only other way to check the used version is to analyze the very verbose debug logs that are generated during the rulebase loading.

**Comment by Tiihott** [comment]
> there is no way to test loaded rulebase version before using it?

After some further testing in C code, it seems like the library context can be used to access a variable that can indicate which version of the rulebase the context is using.
Before any rulebase is loaded the variable is set to 0, after loading the variable is set to 1 or 2 depending on the rulebase version.

**Comment by Tiihott** [comment]
Implemented rulebaseVersion() method that returns the rulebase version that the context is currently using, replacing the file-based version check.
Commit: eeb7885d236d88d84f29e99f079f23d5b49be970

**Review by kortemik — APPROVED** [review]
